apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 484664583769.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 484664583769.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: d8409e97
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
